#!/bin/bash

RED='\033[1;31m'
NC='\033[0m'
REGEX_ISSUE_ID="^(TEST-[0-9]+|develop|release|dev-New-Project)"

ISSUE_ID_IN_BRANCH=$(echo $(git rev-parse --abbrev-ref HEAD) | grep -o -E "$REGEX_ISSUE_ID")

if [[ -z "$ISSUE_ID_IN_BRANCH" ]]; then
    echo -e "${RED} ❌ [pre-commit-hook]:${NC} Your branch name is illegal. Please rename your branch with using following regex: $REGEX_ISSUE_ID"
    exit 1
fi
